version: '3.8'

services:
  # --- 1. ZIPKIN (TRACING) ---
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - obs-net
    restart: always

  # --- 2. PROMETHEUS (MÉTRICAS) ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro # Monta config
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - obs-net
    restart: always

  # --- 3. ALERTMANAGER (ALERTAS) ---
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/config.yml:ro # Monta config
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - "9093:9093"
    networks:
      - obs-net
    restart: always

  # --- 4. GRAFANA (VISUALIZAÇÃO) ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - obs-net
    volumes:
      - grafana_data:/var/lib/grafana
    user: "472"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    
  # --- 5. NODE EXPORTER (MÉTRICAS DO SERVIDOR HOST) ---
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    # Estas montagens são essenciais para que o exporter possa ler métricas do seu Debian
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    ports:
      - "9100:9100"
    networks:
      - obs-net
    restart: always


networks:
  obs-net:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}
